apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: MY-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    ssh:
      publicKeyName: eks-admin
